#if CLIP_TOKENIZER_AVAILABLE
using System.Text.Json;
using LightRAG.Unity.MobileCLIP;

namespace LightRAG.Core.Tests;

/// <summary>
/// Validates that the C# CLIP BPE tokenizer (the actual Unity file) produces token ids identical to
/// Python's open_clip tokenizer for MobileCLIP2-S2. Reference ids are generated by open_clip and the
/// vocab is the standard bpe_simple_vocab_16e6.txt.gz. Skips if those artifacts are absent.
/// </summary>
public class ClipTokenizerParityTests
{
    private const string VocabPath = "/tmp/bpe_simple_vocab_16e6.txt.gz";
    private const string RefPath = "/tmp/clip_ref_tokens.json";

    [Fact]
    public void Matches_open_clip_token_ids()
    {
        if (!File.Exists(VocabPath) || !File.Exists(RefPath))
        {
            return; // artifacts not present in this environment; nothing to compare
        }

        var tokenizer = new ClipBpeTokenizer(VocabPath);
        using var doc = JsonDocument.Parse(File.ReadAllText(RefPath));

        var failures = new List<string>();
        foreach (var entry in doc.RootElement.EnumerateArray())
        {
            var text = entry.GetProperty("text").GetString()!;
            var expected = entry.GetProperty("ids").EnumerateArray().Select(e => e.GetInt32()).ToArray();
            var actual = tokenizer.Tokenize(text);

            if (!expected.SequenceEqual(actual))
            {
                var firstDiff = Enumerable.Range(0, Math.Min(expected.Length, actual.Length))
                    .FirstOrDefault(i => expected[i] != actual[i], -1);
                failures.Add($"\"{text}\" diverges at idx {firstDiff}: exp[{string.Join(",", expected.Take(16))}] act[{string.Join(",", actual.Take(16))}]");
            }
        }

        Assert.True(failures.Count == 0, "CLIP tokenizer mismatch:\n" + string.Join("\n", failures));
    }
}
#endif
